### ISSUE TITLE
First screenshot too small

### ISSUE THREAD

**Issue by paulolieuthier** [QtDesktop/screengrab#15]
When opening screengrab, the automatic first screenshot has a fixed small size. After resizing the window, the screenshot gets expanded.

**Comment by DOOMer** [comment]
I'm made some refactoring interaction between classes Core and MainWindow. Now starting app and resize mainwindow to non-default size, makes the scale preview as on this screenshot.

![sg_2_rigth_rsize](https://cloud.githubusercontent.com/assets/390507/5604107/4ca7d9be-93b8-11e4-83fc-97428d2d4a65.png)

Now i not release any new code, because it very  broken (not worked modules). I plan make new commits in the next weekend.

**Comment by paulolieuthier** [comment]
Nice! Looking forward to seeing it.

**Comment by paulolieuthier** [comment]
@DOOMer how is it going?

**Comment by DOOMer** [comment]
@paulolieuthier, sorry, I'm was very busy on the past weeke on my base work. And i found regression in my new code - after refactoring application have big memory usage (~50 megabytes).  I want made profiling of the new code (and cleanup code because it contains many old not worked in few next days.

**Comment by paulolieuthier** [comment]
Push it to a separate branch.

**Comment by DOOMer** [comment]
Done 		
But this code is not have  worked modules for uploading and editing screenshots. This be add on the next week.
